### PR TITLE
Please read the message

### PR DESCRIPTION
**Pull request by zarEclEC**
Sorry if I use this PR to contact you, close it, it isn't a merge to do

I only wanted to say to you that there is no way to contact you. Your fork is amazing, I'm using it! Please do at least a [subreddit](https://www.reddit.com/r/Forkgram/) (I can give you mod privileges), or a telegram group, or open the "issue" tab (here in github).

Keep up with the good work!!

### CODE REVIEW

**Comment by 23rd** [comment]
Oh, I appreciate someone else decided to use my fork.
Yes, this is true, it is quite difficult to contact me directly. =)

Reddit: Unfortunately, I'm not the Reddit user and not dwell on this site.
Issues Tab: Opened. For some reason, I forgot to do this from the beginning.
Telegram chat: I can create it but I'm afraid the chat will be with 2-3 people without any discussion. 
Look at members count of channel. =) 
I think audience of my fork is too small for telegram chat. Maybe I'm wrong.

**Comment by zarEclEC** [comment]
Thanks for you reply.


> Oh, I appreciate someone else decided to use my fork.
> Yes, this is true, it is quite difficult to contact me directly. =)

Yeah, it's good and mantained. Can't see why not using it 😄
If I knew how to build it, I may be even able to help you in future, I can code. For now, I'll just stick to bug reports or feature request, if you'll accept them, of course.

I'll be advertising this fork, with your permission, in the future.

> Reddit: Unfortunately, I'm not the Reddit user and not dwell on this site.

It's basically a forum, everyone can post things and everyone can reply, it's divided into arguments, subreddits, please do check [r/Telegram](https://www.reddit.com/r/telegram)

> Issues Tab: Opened. For some reason, I forgot to do this from the beginning.

Github sets as closed as default for forks. So it's possible you forgot to do this with other repos on [this group](https://github.com/forkgram)

> Telegram chat: I can create it but I'm afraid the chat will be with 2-3 people without any discussion.
> Look at members count of channel. =)
> I think audience of my fork is too small for telegram chat. Maybe I'm wrong.

You are not wrong. For now, github issues are the best thing that can be done



Well, thanks again for your reply, I'll start with some bugs (if I can find them, of course) and with posting as a feature request the things you wrote in the "projects" section. I'd like to be of some help ^^

**Comment by zarEclEC** [comment]
Good, I've transferred everything in the "todo" column from the project, to the "issue" tab.
That way it's easier to understand at what point everything is in the development ✌

**Comment by zarEclEC** [comment]
I also get that you were using it as a way to track what to do on your own, but that's a better tool for it, it's called "milestone", please have a look [https://github.com/Forkgram/tdesktop/milestones](https://github.com/Forkgram/tdesktop/milestones)

You have to create a milestone, let's say "v0.01" and go to every issues and set for them the milestone you want to give them

**Comment by 23rd** [comment]
Well, thank you for trying, but transfering projects to issues is not good idea. =)
In past year I could move cards from "To Do" to "Done" but for now for some reason I cant do this, so I just left it as it is.
Some things will never be done.

`I also get that you were using it as a way to track what to do on your own, but that's a better tool for it, it's called "milestone", please have a look https://github.com/Forkgram/tdesktop/milestones`
Yeah, I know milestones, but I don't see how they can help me.
At first I thought about making my own version branch in the future.
But now I think the easiest way is to have the identical version with the official branch. It is simple for users and it is simple for me.
So if I'm adding a feature, I just wait for the official release, to release my own new version as something like a bundle — with official changes and with my new feature if it exists.
That's why milestones are useless for me. I have no roadmap.

`If I knew how to build it, I may be even able to help you in future, I can code.`
If you want to help me, you can try to build linux version.

`I'll be advertising this fork, with your permission, in the future.`
Yes, it will be cool. I'm not good in marketing. =)
Now my fork has autoupdates, so users will not be confused with it and it can spread freely.

**Comment by zarEclEC** [comment]
Thanks for your reply.

Issues and milestones are more useful than projects because everyone, myself included, can comment them, suggest improvements, vote for comments with reactions, etc...

Also if issues are associated to milestones it's easy to mark as done, you just have to close the issue



> Some things will never be done.

So you have nothing in mind? Just merge commits from base? If you want I can suggest features, I've already [did in the base](https://github.com/telegramdesktop/tdesktop/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3AArmeF97+) 

> So if I'm adding a feature, I just wait for the official release, to release my own new version as something like a bundle — with official changes and with my new feature if it exists.

That's good and that's why I'll be using your fork: because it has all feature plus others! Amazing!


> If you want to help me, you can try to build linux version.

Yeah, in the future, now I'm doing some school work

> Yes, it will be cool. I'm not good in marketing.

Well, maybe we need a little time to let it grow (in commits ahead), then we can start spreading. I think we should focus on integrate all others fork's features

**Pull request closed without merging**
