### PR TITLE
Removed account limit

### PR DESCRIPTION
**Pull request by resistancelion**

### CODE REVIEW

**Comment by 23rd** [comment]
Did you test it with local passcode?

**Comment by resistancelion** [comment]
> Did you test it with local passcode?

No

**Comment by 23rd** [comment]
Well, to test it correctly you can build the `dev` version, add 2 accounts, set the local passcode, close the app, rebuild the project with your changes and rerun the app.

**Comment by resistancelion** [comment]
> Well, to test it correctly you can build the `dev` version, add 2 accounts, set the local passcode, close the app, rebuild the project with your changes and rerun the app.

Done. Everything is working

5 accounts
Short passcode (4 symbols)

**Comment by 23rd** [comment]
Oh yeah? Ok, I'll check later.

**Comment by 23rd** [comment]
Hmm, looks like it won't crash with the local passcode, so I think I can merge your changes.
But there are 2 moments:
- I won't merge a credential and a merge commits.
- I want the commit code to be wrapped with `#ifdef` conditions instead of be deleted. For example.
```
#ifdef FORKGRAM_LIMIT_ACCOUNTS
	Expects(_accounts.size() < kMaxAccounts);
#endif // FORKGRAM_LIMIT_ACCOUNTS
```

**Comment by 23rd** [comment]
@resistancelion Should I wait for your changes or should I handle it myself?

**Comment by zarEclEC** [comment]
@23rd I think you should try to do it yourself as @resistancelion is not answering

**Pull request closed without merging**
